version: '3'

services:
  backend:
    image: chat-backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend-server

    ports:
      - '8000:8000'

    restart: always

    depends_on:
      - redis

    networks:
      - chat-net

  redis:
    image: redis
    container_name: redis-server
    restart: always
    ports:
      - '6379:6379'
    networks:
      - chat-net

  frontend:
    image: chat-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend-server

    ports:
      - '8080:8080'

    restart: always

    networks:
      - chat-net

networks:
  chat-net:
    driver: bridge
    name: chat-net